events {
    worker_connections 1024;
    #Defines how many connectoins each worker process can handle.
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    #tells NGINX what Content-Type header to send for different file extensions — so browsers know if they're receiving HTML, CSS, JS, images etc.

    server {
        listen 443 ssl;
        server_name paprzyby.42.fr;
        #Defines one virtual server. Only accepts HTTPS connection on port 443
        #servername ???

        ssl_certificate     /etc/nginx/ssl/paprzyby.42.fr.crt;
        ssl_certificate_key /etc/nginx/ssl/paprzyby.42.fr.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        root  /var/www/html;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass   wordpress:9000;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param  PATH_INFO $fastcgi_path_info;
        }
    }
}
